# Generated by Django 5.1.3 on 2024-12-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lastUpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pointsRemaining',
            field=models.SmallIntegerField(default=0),
        ),
    ]
