# Generated by Django 5.1.3 on 2024-12-25 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0002_rename_description_rule_description'),
        ('vendor', '0002_vendor_lastupdatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('notready', 'notready'), ('active', 'active'), ('inactive', 'inactive'), ('complete', 'complete'), ('extend', 'extend')], default='notready', max_length=10)),
                ('campaignType', models.CharField(default='user-campaign', max_length=20)),
                ('isCumilative', models.BooleanField(default=False)),
                ('targetPoints', models.PositiveIntegerField(default=1)),
                ('targetPurchases', models.PositiveIntegerField(default=1)),
                ('pointsGenerated', models.PositiveIntegerField(default=0)),
                ('purchasesCount', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=20)),
                ('activeRules', models.ManyToManyField(related_name='rulelist', to='rule.rule')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
                ('rulesHistory', models.ManyToManyField(related_name='pastrule', to='rule.rule')),
            ],
        ),
    ]
