# Generated by Django 5.1.3 on 2024-12-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('rule', '0002_rename_description_rule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rulesHistory',
            field=models.ManyToManyField(blank=True, related_name='pastrule', to='rule.rule'),
        ),
    ]
