# Generated by Django 5.1.3 on 2024-12-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_ruleshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lastUpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
