# Generated by Django 5.1.3 on 2024-11-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseregistry', '0001_initial'),
        ('walletpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletpoint',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchaseregistry.purchaseregistry'),
        ),
    ]
