# Generated by Django 5.1.3 on 2024-12-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0002_vendor_lastupdatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=40)),
                ('isDerivePurchaseVal', models.BooleanField(default=False)),
                ('purchasePercentage', models.PositiveSmallIntegerField(default=0)),
                ('isPointLimit', models.BooleanField(default=False)),
                ('pointLimit', models.PositiveSmallIntegerField(default=0)),
                ('presetPoint', models.PositiveSmallIntegerField(default=0)),
                ('daysToExpire', models.PositiveSmallIntegerField(default=100)),
                ('isActive', models.BooleanField(default=True)),
                ('ruleType', models.CharField(default='user-rule', max_length=20)),
                ('isReuseable', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
