# Generated by Django 5.1.3 on 2024-12-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='Description',
            new_name='description',
        ),
    ]
