# Generated by Django 5.1.3 on 2024-12-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0003_campaign_lastupdatedon'),
        ('customer', '0002_customer_lastupdatedon_alter_customer_mobile_and_more'),
        ('rule', '0002_rename_description_rule_description'),
        ('vendor', '0002_vendor_lastupdatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rule')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
