# Generated by Django 5.1.3 on 2024-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_orderreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orderReference',
            field=models.CharField(max_length=30),
        ),
    ]
