# Generated by Django 5.1.3 on 2024-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_orderreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orderReference',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
