# Generated by Django 5.1.3 on 2024-12-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponOrderNo', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('instruction', models.TextField()),
                ('termsconditions', models.TextField()),
                ('expiresOn', models.DateField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('pointsUsed', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
