# Generated by Django 5.1.3 on 2024-12-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('expireOn', models.DateField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('isRedeemed', models.CharField(choices=[('no', 'no'), ('partial', 'partial'), ('yes', 'yes')], default='no', max_length=10)),
                ('balancePoints', models.SmallIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
        ),
    ]
