# Generated by Django 5.1.3 on 2024-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointtransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='balancePoints',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
